### ISSUE TITLE
No binaries built using CMake toolchain in build/

### ISSUE THREAD

**Issue by aayush749** [Gabrielcarvfer/NS3#15]
I followed the steps mentioned at `gabrielcarvfer.github.io/ns3/` website for making MinGW Makefiles using CMake.

I followed exactly as mentioned at `https://gabrielcarvfer.github.io/NS3/installation/terminal` after cloning the repository using `git clone --depth 1 https://github.com/Gabrielcarvfer/NS3.git`. 

Their are several dll files build after running the makefile generated by cmake, and only 4 directories namely:- `c4che`, `include`, `lib` and `scratch`. There is no `build/bin` directory created as mentioned in the tutorial at `https://gabrielcarvfer.github.io/NS3/installation/terminal` section 3.3. As a result I'm unable to run any .cc file (since there is no build/bin/ directory containing an equivalent of `waf` for windows).

There is also this page: `https://gabrielcarvfer.github.io/NS3/installation/ns3waf`, mentioning about a binary called `ns3waf` which is also not at the root dir of the project as mentioned.

I even tried running an example program (`first.cc`) and linked it with the libraries generated using cmake generated makefile. The program compiles and links fine and an executable `exe` is generated, but it terminates itself before starting (even before the `main()` function is called). This I confirmed myself using gdb. Screenshot below:-

![image](https://user-images.githubusercontent.com/62141759/149813710-61bd6c48-c6bb-4a78-9582-994cebbe8318.png)

I'm running on OS: Windows11 CPU: AMD Ryzen 7 4800H, and I didn't use WSL or anything and instead performed all the above mentioned steps in GitBash for windows.

**Comment by Gabrielcarvfer** [comment]
Yes, docs are kind of all over the place since I've been changing things to better align with waf. Binaries should be in build/examples, build/src/modulename/examples and scratch.

ns3waf was renamed to ns3. It is available upstream. https://gitlab.com/nsnam/ns-3-dev

It will fail if you haven't included the path containing the DLLs in your PATH environment variable. If you're using Msys2, use their mingw64 terminal. It also includes msys2/mingw64/bin to the PATH, where mingw/c++ runtime libraries are located.

**Comment by aayush749** [comment]
I had built 2 or 3 times, but the binaries (executable binaries) are only created in the `build/scratch` and `build/scratch/subdir`. No other executable binaries are created. There are though .a binaries generated in the `build/lib` directory and also the `build` directory itself contains a whole lot of dlls. 

When trying to generate makefiles using CMake from this repository [(https://gitlab.com/nsnam/ns-3-dev)](https://gitlab.com/nsnam/ns-3-dev), the CMake generation process fails due to some errors, and makefiles aren't generated. Will just copying and pasting the binary `ns3` to the clone of this github repository (with the build directory containing all the files as mentioned previously) and running it from proper terminal with all paths set work fine?

OR

Is their any commit which contains the things in the same manner as prescribed by the documentations. Please let me know the commit hash which is most close to the documentations.

Thanks

**Comment by Gabrielcarvfer** [comment]
> I had built 2 or 3 times, but the binaries (executable binaries) are only created in the `build/scratch` and `build/scratch/subdir`. No other executable binaries are created.

Which means you haven't enabled neither NS3_EXAMPLES nor NS3_TESTS. 
If you're working from the terminal, go to your cmake cache folder, then run `cmake -DNS3_EXAMPLES=ON -DNS3_TESTS=ON . `. They should be enabled.
Then you can build everything `cmake --build .`. Binaries should be built.

If you're using an IDE, they show you a list of targets and your program should be there.

> Will just copying and pasting the binary `ns3` to the clone of this github repository (with the build directory containing all the files as mentioned previously) and running it from proper terminal with all paths set work fine?

I don't think this will work, since we have changed a ton of stuff since then.

> Is their any commit which contains the things in the same manner as prescribed by the documentations. Please let me know the commit hash which is most close to the documentations.

The docs are all correct, except for ns3waf. Eclipse and Xcode required some extra changes to get them working, so use upstream ns-3-dev for that. CLion is the IDE I've been using from the start and have always worked beautifully.

I plan on updating the docs and the master to 3.36, but isn't worth the trouble right now since I've plenty of stuff to finish for the 3.36 release. 
Hopefully MinGW support will be upstreamed in 3.37.

**Comment by aayush749** [comment]
Thanks a lot. I'm able to generate the executable binaries in all the folders just as you said.. but there is still one problem. If I run the binaries of the examples in `build/examples/tutorials/` directory, from the  `build` directory, I don't get any output.

For example, this is the result of the `hello-simulator.exe` , when ran in the gdb:-
![image](https://user-images.githubusercontent.com/62141759/150320632-76d35328-24b7-4f99-87eb-ed914231242a.png)

But the expected output is `Hello Simulator` coming from the line `NS_LOG_UNCOND ("Hello Simulator");`. 

Am I still missing something?

Thanks

**Comment by Gabrielcarvfer** [comment]
Did you set NS_LOG=ON?

**Comment by aayush749** [comment]
No I didn't. I corrected that and now its working. But I cannot use `./waf --run myprogram` to build and run my own custom `*.cc ` files which I place in `scratch.` What is the alternative for that? How can I run small simple programs?

**Comment by Gabrielcarvfer** [comment]
Yup, no Waf here. Build the program first, then run it directly. Or just use an IDE and make your life easier.

**Comment by aayush749** [comment]
That's fine. But is it possible to use netanim though?

**Comment by aayush749** [comment]
Also is there any way that I can speed up the build process. Even building only my own small programs takes a lot of time due to a lot of linking stuff, and also a lot of modules are built again for some reason. Also, I also saw dlls being linked during builds, that's weird.
Here's a screenshot:-
![image](https://user-images.githubusercontent.com/62141759/150366126-5b21bfaa-1b31-4386-a97c-ce2ad9b28b8e.png)

**Comment by Gabrielcarvfer** [comment]
Yes, it is possible. And you can build it with CMake too (NS3_NETANIM=ON).

Did you install ccache? It is automatically picked up and used if installed. Recompilation should be super fast.
It does re-link stuff due to how I did things. All of them have been fixed upstream and I don't plan of fixing them here anytime soon.

**Comment by aayush749** [comment]
I didn't have ccache installed as I didn't knew about it earlier, but I've installed it now. It is super fast as you said.. Thanks 👍

**Comment by Gabrielcarvfer** [comment]
You're welcome. Going to close this.

**Comment by aayush749** [comment]
I didn't had qt so I guess I'll have to install it first because CMake need qt for building NS3_NETANIM. I'll install it later when I would require . My issue no longer exists and you can close this now if there isn't anything more you need to tell. 
Thanks man.

**Comment by Gabrielcarvfer** [comment]
Netanim requires either Qt4 or Qt5. Probably won't work without changes on Qt6.
