### ISSUE TITLE
Upstream O-RAN module?

### ISSUE THREAD

**Issue by a-andre** [Gabrielcarvfer/NS3#17]
Are there any plans to upstream your O-RAN module?

**Comment by Gabrielcarvfer** [comment]
Hi Andre. I personally don't have any plans to upstream it. I'm not working full time on it, there is still a wack ton of stuff missing, and I took some poetic liberty for the sake of development speed (using json, as python dict, instead of properly implementing a struct for each and every information element/message payload format). Recently joined CTTC, and will probably be working on O-RAN, but not necessarily this implementation.

**Comment by a-andre** [comment]
That's fine. I'll keep using your branch (rebased on upstream/master) then. Thanks for providing it.
